### ISSUE TITLE
Missing parent styles in code snippet

### ISSUE THREAD

**Issue by lauriejones** [chunqiuyiyu/css-centering-explorer#3]
Hi there! Nice work on this. It's a cool tool for a quick reference 🙂 

I noticed this one scenario didn't quite make sense:

![image](https://user-images.githubusercontent.com/11398624/36951001-57547b04-2052-11e8-9486-aa0c52494381.png)

1. This only works because of the `text-align: center;` on the parent element. That should probable be included in the code snippet :+1:

2. I've specified `block` not `inline-*` so a solution with inline-block doesn't quite make sense. _(I know that it kinda has to be inline block for this scenario to work, so maybe the questions should be adjusted)_.

Just thought I'd let you know 🙂

**Comment by chunqiuyiyu** [comment]
@lauriejones I am glad that you like it an thanks for your advice!

1.  It is correct to add the relevant code of parent element. I will fix it.
2. How do you think the questions should be adjusted？

I think that CSS is very complicated. Sometimes we can't put element into right position, maybe we should think the problem of layer. This reference is just for beginner, Good practice depends on your own project and actual demand.
